ci: remove checkout step
Signed-off-by: Justin Chadwell <me@jedevc.com>

diff --git a/.github/workflows/daggerverse-preview.gen.yml b/.github/workflows/daggerverse-preview.gen.yml
--- a/.github/workflows/daggerverse-preview.gen.yml
+++ b/.github/workflows/daggerverse-preview.gen.yml
@@ -21,8 +21,6 @@ jobs:
             - ${{ github.repository == 'dagger/dagger' && 'namespace-experiments:dagger.integration=enabled;dagger.version=0.18.14' || 'ubuntu-24.04' }}
         name: deploy
         steps:
-            - name: Checkout
-              uses: actions/checkout@v4
             - name: scripts/install-dagger.sh
               id: install-dagger
               run: |
@@ -37,10 +35,6 @@ jobs:
                   prefix_dir="$(mktemp -d)"
                 fi
                 printf '%s/bin' "$prefix_dir" >>$GITHUB_PATH
-
-                if [ -f "$DAGGER_VERSION_FILE" ]; then
-                  DAGGER_VERSION=$(cat "$DAGGER_VERSION_FILE" | jq -r .engineVersion)
-                fi
 
                 # If the dagger version is 'latest', set the version back to an empty
                 # string. This allows the install script to detect and install the latest
@@ -59,18 +53,12 @@ jobs:
               run: |
                 #!/bin/bash
 
-                # Detect if a dev engine is available, if so: use that
-                # We don't rely on PATH because the GHA runner messes with that
                 if [[ -n "$_EXPERIMENTAL_DAGGER_CLI_BIN" ]]; then
-                    ls -lh $(dirname $_EXPERIMENTAL_DAGGER_CLI_BIN)
-                    export PATH=$(dirname "$_EXPERIMENTAL_DAGGER_CLI_BIN"):$PATH
-                fi
-                if [[ -n "$USE_DEV_ENGINE" ]]; then
-                  # use runner host baked into the cli for dev jobs
+                  export PATH="$(dirname $_EXPERIMENTAL_DAGGER_CLI_BIN):$PATH"
                   unset _EXPERIMENTAL_DAGGER_RUNNER_HOST
                 fi
 
-                # Run a simple query to "warm up" the engine
+                which dagger
                 dagger version
                 dagger core version
               shell: bash
@@ -88,14 +76,9 @@ jobs:
                     ps aux
                 fi
 
-                # Detect if a dev engine is available, if so: use that
-                # We don't rely on PATH because the GHA runner messes with that
                 if [[ -n "$_EXPERIMENTAL_DAGGER_CLI_BIN" ]]; then
-                    export PATH=$(dirname "$_EXPERIMENTAL_DAGGER_CLI_BIN"):$PATH
-                fi
-                # use runner host baked into the cli for dev jobs
-                if [[ -n "$USE_DEV_ENGINE" ]]; then
-                  unset _EXPERIMENTAL_DAGGER_RUNNER_HOST
+                    export PATH="$(dirname $_EXPERIMENTAL_DAGGER_CLI_BIN):$PATH"
+                    unset _EXPERIMENTAL_DAGGER_RUNNER_HOST
                 fi
 
                 GITHUB_STEP_SUMMARY="${GITHUB_STEP_SUMMARY:=github-summary.md}"
@@ -103,8 +86,8 @@ jobs:
 
                 # Ensure the command is provided as an environment variable
                 if [ -z "$COMMAND" ]; then
-                  echo "Error: Please set the COMMAND environment variable."
-                  exit 1
+                    echo "Error: Please set the COMMAND environment variable."
+                    exit 1
                 fi
 
                 tmp=$(mktemp -d)
@@ -116,39 +99,39 @@ jobs:
 
                     # Set up tee to capture and display stdout and stderr
                     if [ -n "$NO_OUTPUT" ]; then
-                        tee stdout.txt < stdout.fifo > /dev/null &
-                        tee stderr.txt < stderr.fifo > /dev/null &
+                        tee stdout.txt <stdout.fifo >/dev/null &
+                        tee stderr.txt <stderr.fifo >/dev/null &
                     else
-                        tee stdout.txt < stdout.fifo &
-                        tee stderr.txt < stderr.fifo >&2 &
+                        tee stdout.txt <stdout.fifo &
+                        tee stderr.txt <stderr.fifo >&2 &
                     fi
                 )
 
                 # Append values to .env
                 if [[ -n "$DOTENV" ]]; then
-                  echo >> .env
-                  echo "$DOTENV" >> .env
+                    echo >>.env
+                    echo "$DOTENV" >>.env
                 fi
 
                 # Run the command, capturing stdout and stderr in the FIFOs
                 set +e
-                eval "$COMMAND" > $tmp/stdout.fifo 2> $tmp/stderr.fifo
+                eval "$COMMAND" >$tmp/stdout.fifo 2>$tmp/stderr.fifo
                 EXIT_CODE=$?
                 set -e
                 # Wait for all background jobs to finish
                 wait
 
                 # Extra trace URL
-                TRACE_URL=$(sed -En 's/^Full trace at (.*)/\1/p' < $tmp/stderr.txt)
+                TRACE_URL=$(sed -En 's/^Full trace at (.*)/\1/p' <$tmp/stderr.txt)
 
                 {
-                cat <<'.'
+                    cat <<'.'
                 ## Dagger trace
 
                 .
 
-                if [[ "$TRACE_URL" == *"rotate dagger.cloud token for full url"* ]]; then
-                    cat <<.
+                    if [[ "$TRACE_URL" == *"rotate dagger.cloud token for full url"* ]]; then
+                        cat <<.
                 Cloud token must be rotated. Please follow these steps:
 
                 1. Go to [Dagger Cloud](https://dagger.cloud)
@@ -157,22 +140,22 @@ jobs:
                 4. Click on "Regenerate token"
                 5. Update the [\`DAGGER_CLOUD_TOKEN\` secret in your GitHub repository settings](https://github.com/${GITHUB_REPOSITORY:?Error: GITHUB_REPOSITORY is not set}/settings/secrets/actions/DAGGER_CLOUD_TOKEN)
                 .
-                elif [ -n "$TRACE_URL" ]; then
-                    echo "[$TRACE_URL]($TRACE_URL)"
-                else
-                    echo "No trace available. To setup: [https://dagger.cloud/traces/setup](https://dagger.cloud/traces/setup)"
-                fi
+                    elif [ -n "$TRACE_URL" ]; then
+                        echo "[$TRACE_URL]($TRACE_URL)"
+                    else
+                        echo "No trace available. To setup: [https://dagger.cloud/traces/setup](https://dagger.cloud/traces/setup)"
+                    fi
 
-                cat <<'.'
+                    cat <<'.'
 
                 ## Dagger version
 
                 ```
                 .
 
-                dagger version
+                    dagger version
 
-                cat <<'.'
+                    cat <<'.'
                 ```
 
                 ## Pipeline command
@@ -180,10 +163,10 @@ jobs:
                 ```bash
                 .
 
-                echo "DAGGER_MODULE=$DAGGER_MODULE \\"
-                echo " $COMMAND"
+                    echo "DAGGER_MODULE=$DAGGER_MODULE \\"
+                    echo " $COMMAND"
 
-                cat <<'.'
+                    cat <<'.'
                 ```
 
                 ## Pipeline output
@@ -191,9 +174,9 @@ jobs:
                 ```
                 .
 
-                cat $tmp/stdout.txt
+                    cat $tmp/stdout.txt
 
-                cat <<'.'
+                    cat <<'.'
                 ```
 
                 ## Pipeline logs
@@ -201,9 +184,9 @@ jobs:
                 ```
                 .
 
-                tail -n 1000 $tmp/stderr.txt
+                    tail -n 1000 $tmp/stderr.txt
 
-                cat <<'.'
+                    cat <<'.'
                 ```
                 .
 
@@ -214,7 +197,6 @@ jobs:
 
                 exit $EXIT_CODE
               env:
-                _EXPERIMENTAL_DAGGER_CLOUD_TOKEN: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                 COMMAND: dagger call -q --github-token=env:RELEASE_DAGGER_CI_TOKEN deploy-preview-with-dagger-main --target ${{ github.event.number }} --github-assignee $GITHUB_ACTOR
                 DAGGER_CLOUD_TOKEN: dag_dagger_sBIv6DsjNerWvTqt2bSFeigBUqWxp9bhh3ONSSgeFnw
                 DAGGER_MODULE: modules/daggerverse
